apiVersion: apps/v1
kind: Deployment
metadata:
  name: abbreve
  tier: frontend
  environment: deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: abbreve
  template:
    metadata:
      labels:
        app: abbreve
      annotations:
        kubernetes.io/change-cause: "release v1"
    spec:
      containers:
      - name: abbreve
        image: "ajimbong/abbreve"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: abbreve-svc
spec:
  type: NodePort
  selector:
    app: abbreve
  ports:
  - port: 80
    targetPort: 80
    # applies only for service type: 
    # NodePort
    nodePort: 30000
