# it's better to use the
# imperative approach to
# create secrets in kub-
# ebernetes.

# that's why there's no
# demo here yet, but we
# willl look at some c-
# ommands very soon

# there is a tool called
# VAULT by Hashicorp tha
# t we can use for manag
# ing our k8s secrets


# run this first:
# kubectl create secret generic mysecret --from-literal=ajim-pass="Hello this is Ajim's secret"



apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets
spec:
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      containers:
      - name: secrets
        image: busybox
        args:
          - "sleep"
          - "infinity"
          - "&&"
          - "env"
        env:
          - name: AJIM_SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: ajim-pass
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"