apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  volumeMode: Filesystem

# ERROR: The PersistentVolume "example-pv" is invalid: spec: 
# Required value: must specify a volume type


#This usually occurs when the underlying storage class uses a 
#provisioner to create your storage. The cloud provider is avoiding 
#allocating storage that’s not actively used in your cluster. If this 
#happens, you should use dynamic volume creation to automatically 
#create a persistent volume at the time it’s used. This is covered in the next section.


# LINK TO ARTICLE: https://earthly.dev/blog/kubernetes-persistent-volumes/

# DOCUMENTATION ON DO: https://docs.digitalocean.com/products/kubernetes/how-to/add-volumes/

# KUBERNETES OFFICIAL DOCUMENTATION: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
